In [1]:
# https://housing.com/in/buy/searches/P1od1w26jrfqap1jlS1Uw5eoY1

In [2]:
from bs4 import BeautifulSoup

with open('./Search -- P1od1w26jrfqap1jlS1Uw5eoY1.html', 'r', encoding='utf-8') as f:
    html = f.read()

soup = BeautifulSoup(html, 'html.parser')

In [3]:
pip show natsort

Name: natsort
Version: 8.4.0
Summary: Simple yet flexible natural sorting in Python.
Home-page: https://github.com/SethMMorton/natsort
Author: Seth M. Morton
Author-email: drtuba78@gmail.com
License: MIT
Location: /home/jain/anaconda3/envs/myenv/lib/python3.12/site-packages
Requires:
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [4]:
from natsort import natsorted

In [5]:

# Find all the div elements that satisfy the given condition
div_elements = soup.select('div.T_configContainer[data-q=property-config] > div.T_configurationStyle')

# Create an empty list to store the text values
text_values = []

# Iterate over the div elements and extract the text values
for div in div_elements:
    text_values.append(div.get_text(strip=True))

# Print the list of text values
print(text_values)

['50 sq.yd Plot', '100 sq.yd Plot', '150 sq.yd Plot', '200 sq.yd Plot', '1 BHK Flat', '2 BHK Flat', '450 sq.ft Plot', '675 sq.ft Plot', '900 sq.ft Plot', '1251 sq.ft Plot', '1323 sq.ft Plot', '1611 sq.ft Plot', '1800 sq.ft Plot', '2205 sq.ft Plot', '4680 sq.ft Plot', '1 BHK Flat', '2 BHK Flat', '3 BHK Flat', '1 BHK Flat', '3 BHK Flat', '1 BHK Flat', '3 BHK Flat', '1 BHK Flat', '2 BHK Flat', '1 BHK Flat', '2 BHK Flat', '1 BHK Flat', '2 BHK Flat', '1 BHK Flat', '2 BHK Flat', '3 BHK Flat', '50 sq.yd Plot', '55 sq.yd Plot', '58 sq.yd Plot', '60 sq.yd Plot', '70 sq.yd Plot', '83 sq.yd Plot', '90 sq.yd Plot', '92 sq.yd Plot', '100 sq.yd Plot', '105 sq.yd Plot', '128 sq.yd Plot', '133 sq.yd Plot', '135 sq.yd Plot', '143 sq.yd Plot', '145 sq.yd Plot', '145 sq.yd Plot', '150 sq.yd Plot', '200 sq.yd Plot', '1 BHK Flat', '2 BHK Flat', '1 BHK Flat', '2 BHK Flat', '3 BHK Flat', 'Studio Apartment', '2 BHK Flat', '50 sq.yd Plot', '100 sq.yd Plot', '450 sq.ft Plot', '693 sq.ft Plot', '900 sq.ft Plot', '1215 sq.ft Plot', '1 BHK Flat', '450 sq.ft Plot', '477 sq.ft Plot', '630 sq.ft Plot', '693 sq.ft Plot', '900 sq.ft Plot', '1188 sq.ft Plot', '1215 sq.ft Plot', '1269 sq.ft Plot', '1323 sq.ft Plot', '1332 sq.ft Plot', '1350 sq.ft Plot', '1395 sq.ft Plot', '1449 sq.ft Plot', '1485 sq.ft Plot', '450 sq.ft Plot', '900 sq.ft Plot']

In [6]:
property_types = list(natsorted(list(set(text_values))))

In [7]:
pip show pandas

Name: pandas
Version: 2.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2023, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 Copyright (c) 2010-2019 Keith Goodman
 Copyright (c) 2019 Bottleneck Developers
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

     * Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.Copyright 2017- Paul Ganssle <paul@ganssle.io>
 Copyright 2017- dateutil contributors (see AUTHORS file)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 The above license applies to all contributions after 2017-12-01, as well as
 all contributions that have been re-licensed (see AUTHORS file for the list of
 contributors who have re-licensed their code).
 --------------------------------------------------------------------------------
 dateutil - Extensions to the standard Python datetime module.

 Copyright (c) 2003-2011 - Gustavo Niemeyer <gustavo@niemeyer.net>
 Copyright (c) 2012-2014 - Tomi Pieviläinen <tomi.pievilainen@iki.fi>
 Copyright (c) 2014-2016 - Yaron de Leeuw <me@jarondl.net>
 Copyright (c) 2015-     - Paul Ganssle <paul@ganssle.io>
 Copyright (c) 2015-     - dateutil contributors (see AUTHORS file)

 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

     * Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.
     * Neither the name of the copyright holder nor the names of its
       contributors may be used to endorse or promote products derived from
       this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 The above BSD License Applies to all code, even that also covered by Apache 2.0.# MIT License

 Copyright (c) 2019 Hadley Wickham; RStudio; and Evan Miller

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 Based on http://opensource.org/licenses/MIT

 This is a template. Complete and ship as file LICENSE the following 2
 lines (only)

 YEAR:
 COPYRIGHT HOLDER:

 and specify as

 License: MIT + file LICENSE

 Copyright (c) <YEAR>, <COPYRIGHT HOLDER>

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 The MIT License

 Copyright (c) 2008-     Attractive Chaos <attractor@live.co.uk>

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.musl as a whole is licensed under the following standard MIT license:

 ----------------------------------------------------------------------
 Copyright © 2005-2020 Rich Felker, et al.

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ----------------------------------------------------------------------

 Authors/contributors include:

 A. Wilcox
 Ada Worcester
 Alex Dowad
 Alex Suykov
 Alexander Monakov
 Andre McCurdy
 Andrew Kelley
 Anthony G. Basile
 Aric Belsito
 Arvid Picciani
 Bartosz Brachaczek
 Benjamin Peterson
 Bobby Bingham
 Boris Brezillon
 Brent Cook
 Chris Spiegel
 Clément Vasseur
 Daniel Micay
 Daniel Sabogal
 Daurnimator
 David Carlier
 David Edelsohn
 Denys Vlasenko
 Dmitry Ivanov
 Dmitry V. Levin
 Drew DeVault
 Emil Renner Berthing
 Fangrui Song
 Felix Fietkau
 Felix Janda
 Gianluca Anzolin
 Hauke Mehrtens
 He X
 Hiltjo Posthuma
 Isaac Dunham
 Jaydeep Patil
 Jens Gustedt
 Jeremy Huntwork
 Jo-Philipp Wich
 Joakim Sindholt
 John Spencer
 Julien Ramseier
 Justin Cormack
 Kaarle Ritvanen
 Khem Raj
 Kylie McClain
 Leah Neukirchen
 Luca Barbato
 Luka Perkov
 M Farkas-Dyck (Strake)
 Mahesh Bodapati
 Markus Wichmann
 Masanori Ogino
 Michael Clark
 Michael Forney
 Mikhail Kremnyov
 Natanael Copa
 Nicholas J. Kain
 orc
 Pascal Cuoq
 Patrick Oppenlander
 Petr Hosek
 Petr Skocik
 Pierre Carrier
 Reini Urban
 Rich Felker
 Richard Pennington
 Ryan Fairfax
 Samuel Holland
 Segev Finer
 Shiz
 sin
 Solar Designer
 Stefan Kristiansson
 Stefan O'Rear
 Szabolcs Nagy
 Timo Teräs
 Trutz Behn
 Valentin Ochs
 Will Dietz
 William Haddon
 William Pitcock

 Portions of this software are derived from third-party works licensed
 under terms compatible with the above MIT license:

 The TRE regular expression implementation (src/regex/reg* and
 src/regex/tre*) is Copyright © 2001-2008 Ville Laurikari and licensed
 under a 2-clause BSD license (license text in the source files). The
 included version has been heavily modified by Rich Felker in 2012, in
 the interests of size, simplicity, and namespace cleanliness.

 Much of the math library code (src/math/* and src/complex/*) is
 Copyright © 1993,2004 Sun Microsystems or
 Copyright © 2003-2011 David Schultz or
 Copyright © 2003-2009 Steven G. Kargl or
 Copyright © 2003-2009 Bruce D. Evans or
 Copyright © 2008 Stephen L. Moshier or
 Copyright © 2017-2018 Arm Limited
 and labelled as such in comments in the individual source files. All
 have been licensed under extremely permissive terms.

 The ARM memcpy code (src/string/arm/memcpy.S) is Copyright © 2008
 The Android Open Source Project and is licensed under a two-clause BSD
 license. It was taken from Bionic libc, used on Android.

 The AArch64 memcpy and memset code (src/string/aarch64/*) are
 Copyright © 1999-2019, Arm Limited.

 The implementation of DES for crypt (src/crypt/crypt_des.c) is
 Copyright © 1994 David Burren. It is licensed under a BSD license.

 The implementation of blowfish crypt (src/crypt/crypt_blowfish.c) was
 originally written by Solar Designer and placed into the public
 domain. The code also comes with a fallback permissive license for use
 in jurisdictions that may not recognize the public domain.

 The smoothsort implementation (src/stdlib/qsort.c) is Copyright © 2011
 Valentin Ochs and is licensed under an MIT-style license.

 The x86_64 port was written by Nicholas J. Kain and is licensed under
 the standard MIT terms.

 The mips and microblaze ports were originally written by Richard
 Pennington for use in the ellcc project. The original code was adapted
 by Rich Felker for build system and code conventions during upstream
 integration. It is licensed under the standard MIT terms.

 The mips64 port was contributed by Imagination Technologies and is
 licensed under the standard MIT terms.

 The powerpc port was also originally written by Richard Pennington,
 and later supplemented and integrated by John Spencer. It is licensed
 under the standard MIT terms.

 All other files which have no copyright comments are original works
 produced specifically for use as part of this library, written either
 by Rich Felker, the main author of the library, or by one or more
 contibutors listed above. Details on authorship of individual files
 can be found in the git version control history of the project. The
 omission of copyright and license comments in each file is in the
 interest of source tree size.

 In addition, permission is hereby granted for all public header files
 (include/* and arch/*/bits/*) and crt files intended to be linked into
 applications (crt/*, ldso/dlstart.c, and arch/*/crt_arch.h) to omit
 the copyright notice and permission notice otherwise required by the
 license, and to use these files without any requirement of
 attribution. These files include substantial contributions from:

 Bobby Bingham
 John Spencer
 Nicholas J. Kain
 Rich Felker
 Richard Pennington
 Stefan Kristiansson
 Szabolcs Nagy

 all of whom have explicitly granted such permission.

 This file previously contained text expressing a belief that most of
 the files covered by the above exception were sufficiently trivial not
 to be subject to copyright, resulting in confusion over whether it
 negated the permissions granted in the license. In the spirit of
 permissive licensing, and of not having licensing issues being an
 obstacle to adoption, that text has been removed.Copyright (c) 2005-2023, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                  Apache License
                            Version 2.0, January 2004
                         http://www.apache.org/licenses/

    TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

    1. Definitions.

       "License" shall mean the terms and conditions for use, reproduction,
       and distribution as defined by Sections 1 through 9 of this document.

       "Licensor" shall mean the copyright owner or entity authorized by
       the copyright owner that is granting the License.

       "Legal Entity" shall mean the union of the acting entity and all
       other entities that control, are controlled by, or are under common
       control with that entity. For the purposes of this definition,
       "control" means (i) the power, direct or indirect, to cause the
       direction or management of such entity, whether by contract or
       otherwise, or (ii) ownership of fifty percent (50%) or more of the
       outstanding shares, or (iii) beneficial ownership of such entity.

       "You" (or "Your") shall mean an individual or Legal Entity
       exercising permissions granted by this License.

       "Source" form shall mean the preferred form for making modifications,
       including but not limited to software source code, documentation
       source, and configuration files.

       "Object" form shall mean any form resulting from mechanical
       transformation or translation of a Source form, including but
       not limited to compiled object code, generated documentation,
       and conversions to other media types.

       "Work" shall mean the work of authorship, whether in Source or
       Object form, made available under the License, as indicated by a
       copyright notice that is included in or attached to the work
       (an example is provided in the Appendix below).

       "Derivative Works" shall mean any work, whether in Source or Object
       form, that is based on (or derived from) the Work and for which the
       editorial revisions, annotations, elaborations, or other modifications
       represent, as a whole, an original work of authorship. For the purposes
       of this License, Derivative Works shall not include works that remain
       separable from, or merely link (or bind by name) to the interfaces of,

In [8]:
import pandas as pd

In [9]:
dict_for_df = {k:[] for k in property_types}
dict_for_df['property_title'] = []
dict_for_df['avg_price'] = []
dict_for_df['possession'] =[]
dict_for_df['seller_label'] = []
dict_for_df['seller_subtitle'] = []
dict_for_df['project'] = []
dict_for_df['single_price'] = []
dict_for_df['builtup_area'] = []

In [10]:
df = pd.DataFrame(dict_for_df)

In [11]:
df

Empty DataFrame
Columns: [1 BHK Flat, 2 BHK Flat, 3 BHK Flat, 50 sq.yd Plot, 55 sq.yd Plot, 58 sq.yd Plot, 60 sq.yd Plot, 70 sq.yd Plot, 83 sq.yd Plot, 90 sq.yd Plot, 92 sq.yd Plot, 100 sq.yd Plot, 105 sq.yd Plot, 128 sq.yd Plot, 133 sq.yd Plot, 135 sq.yd Plot, 143 sq.yd Plot, 145 sq.yd Plot, 150 sq.yd Plot, 200 sq.yd Plot, 450 sq.ft Plot, 477 sq.ft Plot, 630 sq.ft Plot, 675 sq.ft Plot, 693 sq.ft Plot, 900 sq.ft Plot, 1188 sq.ft Plot, 1215 sq.ft Plot, 1251 sq.ft Plot, 1269 sq.ft Plot, 1323 sq.ft Plot, 1332 sq.ft Plot, 1350 sq.ft Plot, 1395 sq.ft Plot, 1449 sq.ft Plot, 1485 sq.ft Plot, 1611 sq.ft Plot, 1800 sq.ft Plot, 2205 sq.ft Plot, 4680 sq.ft Plot, Studio Apartment, property_title, avg_price, possession, seller_label, seller_subtitle, project, single_price, builtup_area]
Index: []

[0 rows x 49 columns]

In [12]:
import re

In [13]:
# Iterate over div.infoTopContainer to process the inner contents of these div in a for loop
for div in soup.select('div.infoTopContainer'):
    # Process the contents of each div.infoTopContainer
    #print(div)
    
    my_row = {}

    # from this div , fetch div class="title-style"
    title_div = div.select_one('div.title-style')
    if title_div:
        my_row['project'] = title_div.text
        # print(title_div.text)
    else:
        my_row['project'] = "NA"

    
    # from the div, fetch h2 class="subtitle-style" or h2 class="title-style"
    subtitle_div = div.select_one('h2.subtitle-style') or div.select_one('h2.title-style')
    if subtitle_div:
        my_row['property_title'] = subtitle_div.text.strip()
        # print(subtitle_div.text.strip())
    else:
        my_row['property_title'] = "NA"

    
    pricing_dict = {}
    # from this div, fetch all of the div.T_configContainer[data-q=property-config]
    config_containers = div.select('div.T_configContainer[data-q=property-config]')
    for config_container in config_containers:
        lines = config_container.text.splitlines()
        pricing_dict[lines[2].strip()] = lines[4].strip()
    
    my_row.update(pricing_dict)
    # print(pricing_dict)
    
    
    
    # from this div, fetch div.T_configurationStyle[data-q=avg-price]
    avg_price_div = div.select_one('div.T_configurationStyle[data-q=avg-price]')
    if avg_price_div:
        avg_price = avg_price_div.text
    else:
        # from this div, fetch div.property-detail[data-q=property-detail]
        property_detail_div = div.select_one('div.property-detail[data-q=property-detail]')
        if property_detail_div:
            avg_price = property_detail_div.text.split("•")[0].strip()
            # print(property_detail_div.text)
        else:
            avg_price = "NA"
        
    my_row['avg_price'] = avg_price.split(":")[1].strip()
    



    # from this div, fetch div.T_singlePriceStyle[data-q=price]
    price_div = div.select_one('div.T_singlePriceStyle[data-q=price]')
    if price_div:
        my_row["single_price"] = re.sub(r'\s', '', price_div.text)
    else: 
        my_row["single_price"] = "NA"
    
    # from this div, fetch first child of div.T_configContainer[data-q=builtup-area]
    builtup_area_div = div.select_one('div.T_configContainer[data-q=builtup-area]')
    if builtup_area_div:
        my_row['builtup_area'] = builtup_area_div.text.splitlines()[2].strip()
    else:
        my_row['builtup_area'] = "NA"    
    
    print(my_row)
    dict_for_df.update(my_row)
    
    for key, value in dict_for_df.items():
        if isinstance(value, list) and len(value) == 0:
            dict_for_df[key] = 'NA'
    
    df = pd.concat([df, pd.DataFrame([dict_for_df])], ignore_index=True)

{'project': 'RBSM Colony Part 1', 'property_title': 'Residential Plots  in New Palam Vihar Phase 1, Sector 110', '50 sq.yd Plot': '₹13 L', '100 sq.yd Plot': '₹26 L', '150 sq.yd Plot': '₹39 L', '200 sq.yd Plot': '₹52 L', 'avg_price': '₹2.89k/sq.yd', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'DLF Chisholm Apartments', 'property_title': '1, 2 BHK Flats  in Sector 25, DLF Phase 2', '1 BHK Flat': '₹11.25 L - 20.25 L', '2 BHK Flat': '₹24.75 L - 42.75 L', 'avg_price': '₹4.5 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'SDH Rose City', 'property_title': 'Residential Plots  in Rajoria Nagar', '450 sq.ft Plot': '₹3.5 L', '675 sq.ft Plot': '₹5.24 L', '900 sq.ft Plot': '₹6.99 L', '1251 sq.ft Plot': '₹9.72 L', '1323 sq.ft Plot': '₹10.28 L', '1611 sq.ft Plot': '₹12.52 L', '1800 sq.ft Plot': '₹13.99 L', '2205 sq.ft Plot': '₹17.13 L', '4680 sq.ft Plot': '₹36.36 L', 'avg_price': '₹777.0/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Adore Prosperity Homes', 'property_title': '1, 2, 3 BHK Flats  in Sector 35, Sohna', '1 BHK Flat': '₹14.66 L - 14.7 L', '2 BHK Flat': '₹21.24 L - 21.26 L', '3 BHK Flat': '₹27.48 L - 27.54 L', 'avg_price': '₹3.02 K - ₹4.5 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Mahira Homes 104', 'property_title': '1, 3 BHK Flats  in Tech Chand Nagar, Sector 104', '1 BHK Flat': '₹13.84 L - 26.4 L', '3 BHK Flat': '₹26.29 L - 26.4 L', 'avg_price': 'Dec, 2025', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Czar Mahira Homes 63A', 'property_title': '1, 3 BHK Flats  in Sector 63A, Kadarpur', '1 BHK Flat': '₹12.96 L', '3 BHK Flat': '₹25.8 L', 'avg_price': '₹4 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Sunrays Heights', 'property_title': '1, 2 BHK Flats  in Kadarpur', '1 BHK Flat': '₹14.6 L - 15.08 L', '2 BHK Flat': '₹14.6 L - 25.0 L', 'avg_price': '₹4.09 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Omaxe Europia', 'property_title': '1, 2 BHK Flats  in Thara', '1 BHK Flat': '₹14.98 L', '2 BHK Flat': '₹24.95 L', 'avg_price': '₹2.75 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Raheja Krishna Housing Scheme', 'property_title': '1, 2 BHK Flats  in Sector 48', '1 BHK Flat': '₹13.25 L - 16.36 L', '2 BHK Flat': '₹17.36 L - 24.61 L', 'avg_price': '₹3.84 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Apex Our Homes 2', 'property_title': '1, 2, 3 BHK Flats  in South City I, Sector 41', '1 BHK Flat': '₹12.16 L', '2 BHK Flat': '₹18.66 L', '3 BHK Flat': '₹24.4 L', 'avg_price': '₹3.8 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'ALD Green Park 2', 'property_title': 'Residential Plots  in Karnki', '50 sq.yd Plot': '₹6 L', '55 sq.yd Plot': '₹6.6 L', '58 sq.yd Plot': '₹7 L', '60 sq.yd Plot': '₹7.2 L', '70 sq.yd Plot': '₹8.4 L', '83 sq.yd Plot': '₹10 L', '90 sq.yd Plot': '₹10.8 L', '92 sq.yd Plot': '₹11.1 L', '100 sq.yd Plot': '₹12 L', '105 sq.yd Plot': '₹12.66 L', '128 sq.yd Plot': '₹15.4 L', '133 sq.yd Plot': '₹15.96 L', '135 sq.yd Plot': '₹16.2 L', '143 sq.yd Plot': '₹17.2 L', '145 sq.yd Plot': '₹17.48 L', '150 sq.yd Plot': '₹18 L', '200 sq.yd Plot': '₹23.99 L', 'avg_price': '₹1.33k/sq.yd', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'OSB Golf Heights', 'property_title': '1, 2 BHK Flats  in Southern Peripheral Road', '1 BHK Flat': '₹14.83 L - 14.91 L', '2 BHK Flat': '₹23.09 L - 23.45 L', 'avg_price': '₹4.1 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Viscaria The Greens', 'property_title': '1, 2, 3 BHK Flats  in Block B, Sushant Lok Phase 1', '1 BHK Flat': '₹12.1 L', '2 BHK Flat': '₹16.72 L', '3 BHK Flat': '₹21.56 L', 'avg_price': '₹2.2 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'Zenext Heights', 'property_title': 'Studio, 2 BHK Flat,Studio Flats  in Manesar', 'Studio Apartment': '₹10 L', '2 BHK Flat': '₹20 L', 'avg_price': '₹3.33 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NKV Plots', 'property_title': 'Residential Plots  in Sector 66', '50 sq.yd Plot': '₹7.5 L', '100 sq.yd Plot': '₹15 L', 'avg_price': '₹1.67k/sq.yd', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NA', 'property_title': 'Residential Plot  in Bhondsi', 'avg_price': '₹1.67k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot  in Maruti Kunj', 'avg_price': '₹2.78k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '540 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Studio  in Sector 70', 'avg_price': '₹3.75k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '400 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat  in Sector 37D', 'avg_price': '₹5.0k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '300 sq.ft'}
{'project': 'NA', 'property_title': '2 BHK Flat  in Ashok Vihar, Sector 3', 'avg_price': '₹1.67k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 BHK Flat  in Dayanand Colony, Sector 6', 'avg_price': '₹2.94k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '510 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Studio  in Sector 70', 'avg_price': '₹6.82k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '220 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot  in Sector 66', 'avg_price': '₹1.67k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot  in IMT Sohna', 'avg_price': '₹1.67k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat  in Sector 86', 'avg_price': '₹6.02k/sq.ft', 'single_price': '₹15.0L', 'builtup_area': '249 sq.ft'}
{'project': 'Parmanad Vaishnao Enclave', 'property_title': 'Residential Plots  in Sector 34 Sohna', '450 sq.ft Plot': '₹5.25 L', '693 sq.ft Plot': '₹8.09 L', '900 sq.ft Plot': '₹10.5 L', '1215 sq.ft Plot': '₹14.78 L', 'avg_price': '₹992.0/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NA', 'property_title': 'Residential Plot  in Shanti Kunj', 'avg_price': '₹2.37k/sq.ft', 'single_price': '₹14.74L', 'builtup_area': '621 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot  in Maruti Kunj', 'avg_price': '₹3.32k/sq.ft', 'single_price': '₹14.65L', 'builtup_area': '441 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat  in Sector 37D', 'avg_price': '₹4.83k/sq.ft', 'single_price': '₹14.5L', 'builtup_area': '300 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat  in Sector 37C', 'avg_price': '₹7.0k/sq.ft', 'single_price': '₹14.0L', 'builtup_area': '200 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹3.11k/sq.ft', 'single_price': '₹14.0L', 'builtup_area': '450 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Studio in Sector 70', 'avg_price': '₹3.5k/sq.ft', 'single_price': '₹14.0L', 'builtup_area': '400 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹2.64k/sq.ft', 'single_price': '₹13.57L', 'builtup_area': '513 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Duplex in Sector 37C', 'avg_price': '₹5.4k/sq.ft', 'single_price': '₹13.5L', 'builtup_area': '250 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Bhondsi', 'avg_price': '₹1.5k/sq.ft', 'single_price': '₹13.5L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹2.66k/sq.ft', 'single_price': '₹13.15L', 'builtup_area': '495 sq.ft'}
{'project': 'Omaxe Marigold', 'property_title': '1 BHK Flat in Kalaka', '1 BHK Flat': '₹6.97 L - 13.09 L', 'avg_price': '₹1.7 K/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NA', 'property_title': 'Residential Plot in Ashok Vihar, Sector 3', 'avg_price': '₹1.44k/sq.ft', 'single_price': '₹13.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Bhondsi', 'avg_price': '₹1.44k/sq.ft', 'single_price': '₹13.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 37D', 'avg_price': '₹3.71k/sq.ft', 'single_price': '₹13.0L', 'builtup_area': '350 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹2.7k/sq.ft', 'single_price': '₹12.88L', 'builtup_area': '477 sq.ft'}
{'project': 'NA', 'property_title': '2 BHK Flat in Laxmi Garden, Sector 11', 'avg_price': '₹3.13k/sq.ft', 'single_price': '₹12.5L', 'builtup_area': '400 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Silani', 'avg_price': '₹1.39k/sq.ft', 'single_price': '₹12.5L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹1.37k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '875 sq.ft'}
{'project': 'NA', 'property_title': '1 BHK Independent House in Bhondsi', 'avg_price': '₹2.67k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '450 sq.ft'}
{'project': 'NA', 'property_title': '1 BHK Independent Builder Floor in Sector 81', 'avg_price': '₹6.0k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '200 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Bhondsi', 'avg_price': '₹1.33k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 37C', 'avg_price': '₹5.45k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '220 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Studio in Sector 70', 'avg_price': '₹3.0k/sq.ft', 'single_price': '₹12.0L', 'builtup_area': '400 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Shanti Kunj', 'avg_price': '₹2.63k/sq.ft', 'single_price': '₹11.14L', 'builtup_area': '423 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Damdma', 'avg_price': '₹1.22k/sq.ft', 'single_price': '₹11.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Masani Village, Sector 6', 'avg_price': '₹1.22k/sq.ft', 'single_price': '₹11.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Dhankot', 'avg_price': '₹2.44k/sq.ft', 'single_price': '₹11.0L', 'builtup_area': '450 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Sector 17 Sohna', 'avg_price': '₹1.12k/sq.ft', 'single_price': '₹10.1L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 37C', 'avg_price': '₹5.0k/sq.ft', 'single_price': '₹10.0L', 'builtup_area': '200 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 90', 'avg_price': '₹5.0k/sq.ft', 'single_price': '₹10.0L', 'builtup_area': '200 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Silani', 'avg_price': '₹1.11k/sq.ft', 'single_price': '₹10.0L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 108', 'avg_price': '₹4.57k/sq.ft', 'single_price': '₹10.0L', 'builtup_area': '219 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Maruti Kunj', 'avg_price': '₹2.0k/sq.ft', 'single_price': '₹10.0L', 'builtup_area': '500 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Sector 11 Sohna', 'avg_price': '₹1.04k/sq.ft', 'single_price': '₹9.4L', 'builtup_area': '900 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Sultanpur', 'avg_price': '₹2.06k/sq.ft', 'single_price': '₹9.25L', 'builtup_area': '450 sq.ft'}
{'project': 'Lotus Monarch City', 'property_title': 'Residential Plots in Bhondsi', '450 sq.ft Plot': '₹2.6 L', '477 sq.ft Plot': '₹2.76 L', '630 sq.ft Plot': '₹3.64 L', '693 sq.ft Plot': '₹4.01 L', '900 sq.ft Plot': '₹5.2 L', '1188 sq.ft Plot': '₹6.87 L', '1215 sq.ft Plot': '₹7.02 L', '1269 sq.ft Plot': '₹7.33 L', '1323 sq.ft Plot': '₹7.65 L', '1332 sq.ft Plot': '₹7.7 L', '1350 sq.ft Plot': '₹7.8 L', '1395 sq.ft Plot': '₹8.06 L', '1449 sq.ft Plot': '₹8.38 L', '1485 sq.ft Plot': '₹8.58 L', 'avg_price': '₹578.0/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 37D', 'avg_price': '₹2.46k/sq.ft', 'single_price': '₹8.0L', 'builtup_area': '325 sq.ft'}
{'project': 'NA', 'property_title': '1 BHK Flat in Rajoria Nagar', 'avg_price': '₹1.25k/sq.ft', 'single_price': '₹7.5L', 'builtup_area': '600 sq.ft'}
{'project': 'NA', 'property_title': '8 BHK Independent House in Rajiv Nagar, Sector 13', 'avg_price': '₹1.36k/sq.ft', 'single_price': '₹7.5L', 'builtup_area': '550 sq.ft'}
{'project': 'NA', 'property_title': '1 RK Flat in Sector 37D', 'avg_price': '₹2.09k/sq.ft', 'single_price': '₹6.8L', 'builtup_area': '325 sq.ft'}
{'project': 'NS Zenext Avenue', 'property_title': 'Residential Plots in Manesar', '450 sq.ft Plot': '₹3.25 L', '900 sq.ft Plot': '₹6.5 L', 'avg_price': '₹722.0/sq.ft', 'single_price': 'NA', 'builtup_area': 'NA'}
{'project': 'NA', 'property_title': 'Residential Plot in Dhankot', 'avg_price': '₹1.0k/sq.ft', 'single_price': '₹4.5L', 'builtup_area': '450 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Sultanpur', 'avg_price': '₹8.5k/sq.yd', 'single_price': '₹4.25L', 'builtup_area': '50 sq.yd'}
{'project': 'NA', 'property_title': 'Residential Plot in Shahid Smarak', 'avg_price': '₹648.00/sq.ft', 'single_price': '₹3.5L', 'builtup_area': '540 sq.ft'}
{'project': 'NA', 'property_title': '2 BHK Flat in Laxman Vihar, Sector 3A', 'avg_price': '₹471.00/sq.ft', 'single_price': '₹3.3L', 'builtup_area': '700 sq.ft'}
{'project': 'NA', 'property_title': 'Residential Plot in Patel Nagar', 'avg_price': '₹944.00/sq.ft', 'single_price': '₹1.7L', 'builtup_area': '180 sq.ft'}

In [14]:
df

,1 BHK Flat,2 BHK Flat,3 BHK Flat,50 sq.yd Plot,55 sq.yd Plot,58 sq.yd Plot,60 sq.yd Plot,70 sq.yd Plot,83 sq.yd Plot,90 sq.yd Plot,...,4680 sq.ft Plot,Studio Apartment,property_title,avg_price,possession,seller_label,seller_subtitle,project,single_price,builtup_area
0,NA,NA,NA,₹13 L,NA,NA,NA,NA,NA,NA,...,NA,NA,"Residential Plots in New Palam Vihar Phase 1,...",₹2.89k/sq.yd,NA,NA,NA,RBSM Colony Part 1,NA,NA
1,₹11.25 L - 20.25 L,₹24.75 L - 42.75 L,NA,₹13 L,NA,NA,NA,NA,NA,NA,...,NA,NA,"1, 2 BHK Flats in Sector 25, DLF Phase 2",₹4.5 K/sq.ft,NA,NA,NA,DLF Chisholm Apartments,NA,NA
2,₹11.25 L - 20.25 L,₹24.75 L - 42.75 L,NA,₹13 L,NA,NA,NA,NA,NA,NA,...,₹36.36 L,NA,Residential Plots in Rajoria Nagar,₹777.0/sq.ft,NA,NA,NA,SDH Rose City,NA,NA
3,₹14.66 L - 14.7 L,₹21.24 L - 21.26 L,₹27.48 L - 27.54 L,₹13 L,NA,NA,NA,NA,NA,NA,...,₹36.36 L,NA,"1, 2, 3 BHK Flats in Sector 35, Sohna",₹3.02 K - ₹4.5 K/sq.ft,NA,NA,NA,Adore Prosperity Homes,NA,NA
4,₹13.84 L - 26.4 L,₹21.24 L - 21.26 L,₹26.29 L - 26.4 L,₹13 L,NA,NA,NA,NA,NA,NA,...,₹36.36 L,NA,"1, 3 BHK Flats in Tech Chand Nagar, Sector 104","Dec, 2025",NA,NA,NA,Mahira Homes 104,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,₹6.97 L - 13.09 L,₹20 L,₹21.56 L,₹7.5 L,₹6.6 L,₹7 L,₹7.2 L,₹8.4 L,₹10 L,₹10.8 L,...,₹36.36 L,₹10 L,Residential Plot in Dhankot,₹1.0k/sq.ft,NA,NA,NA,NA,₹4.5L,450 sq.ft
68,₹6.97 L - 13.09 L,₹20 L,₹21.56 L,₹7.5 L,₹6.6 L,₹7 L,₹7.2 L,₹8.4 L,₹10 L,₹10.8 L,...,₹36.36 L,₹10 L,Residential Plot in Sultanpur,₹8.5k/sq.yd,NA,NA,NA,NA,₹4.25L,50 sq.yd
69,₹6.97 L - 13.09 L,₹20 L,₹21.56 L,₹7.5 L,₹6.6 L,₹7 L,₹7.2 L,₹8.4 L,₹10 L,₹10.8 L,...,₹36.36 L,₹10 L,Residential Plot in Shahid Smarak,₹648.00/sq.ft,NA,NA,NA,NA,₹3.5L,540 sq.ft
70,₹6.97 L - 13.09 L,₹20 L,₹21.56 L,₹7.5 L,₹6.6 L,₹7 L,₹7.2 L,₹8.4 L,₹10 L,₹10.8 L,...,₹36.36 L,₹10 L,"2 BHK Flat in Laxman Vihar, Sector 3A",₹471.00/sq.ft,NA,NA,NA,NA,₹3.3L,700 sq.ft
71,₹6.97 L - 13.09 L,₹20 L,₹21.56 L,₹7.5 L,₹6.6 L,₹7 L,₹7.2 L,₹8.4 L,₹10 L,₹10.8 L,...,₹36.36 L,₹10 L,Residential Plot in Patel Nagar,₹944.00/sq.ft,NA,NA,NA,NA,₹1.7L,180 sq.ft

In [15]:
df.to_csv('1_df.csv', index = False)