In [23]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv('./1_df.csv')

In [24]:
df.columns

Index(['1 BHK Flat', '2 BHK Flat', '3 BHK Flat', '50 sq.yd Plot',
       '55 sq.yd Plot', '58 sq.yd Plot', '60 sq.yd Plot', '70 sq.yd Plot',
       '83 sq.yd Plot', '90 sq.yd Plot', '92 sq.yd Plot', '100 sq.yd Plot',
       '105 sq.yd Plot', '128 sq.yd Plot', '133 sq.yd Plot', '135 sq.yd Plot',
       '143 sq.yd Plot', '145 sq.yd Plot', '150 sq.yd Plot', '200 sq.yd Plot',
       '450 sq.ft Plot', '477 sq.ft Plot', '630 sq.ft Plot', '675 sq.ft Plot',
       '693 sq.ft Plot', '900 sq.ft Plot', '1188 sq.ft Plot',
       '1215 sq.ft Plot', '1251 sq.ft Plot', '1269 sq.ft Plot',
       '1323 sq.ft Plot', '1332 sq.ft Plot', '1350 sq.ft Plot',
       '1395 sq.ft Plot', '1449 sq.ft Plot', '1485 sq.ft Plot',
       '1611 sq.ft Plot', '1800 sq.ft Plot', '2205 sq.ft Plot',
       '4680 sq.ft Plot', 'Studio Apartment', 'property_title', 'avg_price',
       'possession', 'seller_label', 'seller_subtitle', 'project',
       'single_price', 'builtup_area'],
      dtype='object')

In [25]:
df.head()

,1 BHK Flat,2 BHK Flat,3 BHK Flat,50 sq.yd Plot,55 sq.yd Plot,58 sq.yd Plot,60 sq.yd Plot,70 sq.yd Plot,83 sq.yd Plot,90 sq.yd Plot,92 sq.yd Plot,100 sq.yd Plot,105 sq.yd Plot,128 sq.yd Plot,133 sq.yd Plot,135 sq.yd Plot,143 sq.yd Plot,145 sq.yd Plot,150 sq.yd Plot,200 sq.yd Plot,450 sq.ft Plot,477 sq.ft Plot,630 sq.ft Plot,675 sq.ft Plot,693 sq.ft Plot,900 sq.ft Plot,1188 sq.ft Plot,1215 sq.ft Plot,1251 sq.ft Plot,1269 sq.ft Plot,1323 sq.ft Plot,1332 sq.ft Plot,1350 sq.ft Plot,1395 sq.ft Plot,1449 sq.ft Plot,1485 sq.ft Plot,1611 sq.ft Plot,1800 sq.ft Plot,2205 sq.ft Plot,4680 sq.ft Plot,Studio Apartment,property_title,avg_price,possession,seller_label,seller_subtitle,project,single_price,builtup_area
0,NaN,NaN,NaN,₹13 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,₹26 L,NaN,NaN,NaN,NaN,NaN,NaN,₹39 L,₹52 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Residential Plots in New Palam Vihar Phase 1, Sector 110",₹2.89k/sq.yd,NaN,NaN,NaN,RBSM Colony Part 1,NaN,NaN
1,₹11.25 L - 20.25 L,₹24.75 L - 42.75 L,NaN,₹13 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,₹26 L,NaN,NaN,NaN,NaN,NaN,NaN,₹39 L,₹52 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1, 2 BHK Flats in Sector 25, DLF Phase 2",₹4.5 K/sq.ft,NaN,NaN,NaN,DLF Chisholm Apartments,NaN,NaN
2,₹11.25 L - 20.25 L,₹24.75 L - 42.75 L,NaN,₹13 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,₹26 L,NaN,NaN,NaN,NaN,NaN,NaN,₹39 L,₹52 L,₹3.5 L,NaN,NaN,₹5.24 L,NaN,₹6.99 L,NaN,NaN,₹9.72 L,NaN,₹10.28 L,NaN,NaN,NaN,NaN,NaN,₹12.52 L,₹13.99 L,₹17.13 L,₹36.36 L,NaN,Residential Plots in Rajoria Nagar,₹777.0/sq.ft,NaN,NaN,NaN,SDH Rose City,NaN,NaN
3,₹14.66 L - 14.7 L,₹21.24 L - 21.26 L,₹27.48 L - 27.54 L,₹13 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,₹26 L,NaN,NaN,NaN,NaN,NaN,NaN,₹39 L,₹52 L,₹3.5 L,NaN,NaN,₹5.24 L,NaN,₹6.99 L,NaN,NaN,₹9.72 L,NaN,₹10.28 L,NaN,NaN,NaN,NaN,NaN,₹12.52 L,₹13.99 L,₹17.13 L,₹36.36 L,NaN,"1, 2, 3 BHK Flats in Sector 35, Sohna",₹3.02 K - ₹4.5 K/sq.ft,NaN,NaN,NaN,Adore Prosperity Homes,NaN,NaN
4,₹13.84 L - 26.4 L,₹21.24 L - 21.26 L,₹26.29 L - 26.4 L,₹13 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,₹26 L,NaN,NaN,NaN,NaN,NaN,NaN,₹39 L,₹52 L,₹3.5 L,NaN,NaN,₹5.24 L,NaN,₹6.99 L,NaN,NaN,₹9.72 L,NaN,₹10.28 L,NaN,NaN,NaN,NaN,NaN,₹12.52 L,₹13.99 L,₹17.13 L,₹36.36 L,NaN,"1, 3 BHK Flats in Tech Chand Nagar, Sector 104","Dec, 2025",NaN,NaN,NaN,Mahira Homes 104,NaN,NaN

In [26]:


# -------------------------
# PRICE PARSING UTILITIES
# -------------------------

def indian_to_number(x):
    if pd.isna(x):
        return np.nan

    x = str(x).replace("₹", "").replace(",", "").strip().lower()

    # handle ranges
    if "-" in x:
        parts = [p.strip() for p in x.split("-")]
        nums = [indian_to_number(p) for p in parts]
        return min(nums), max(nums)

    # unit conversion
    if x.endswith("k") or x.endswith("k."):
        return float(x.replace("k", "").replace("k.", "")) * 1e3

    if x.endswith("l") or x.endswith("lac") or x.endswith("lakh"):
        return float(re.sub("[^0-9.]", "", x)) * 1e5

    if x.endswith("cr") or x.endswith("crore"):
        return float(re.sub("[^0-9.]", "", x)) * 1e7

    # plain digits
    try:
        return float(re.sub("[^0-9.]", "", x))
    except:
        return np.nan


# ------------------------------------
# NORMALIZE ALL PRICE COLUMNS
# ------------------------------------

price_cols = [c for c in df.columns if "bhk flat" in c.lower() or "sq.yd plot" in c.lower() \
    or "sq.ft plot" in c.lower() or "studio apartment" in c.lower()]

for col in price_cols:
    df[f"{col}_min"] = np.nan
    df[f"{col}_max"] = np.nan

    for i, val in df[col].items():
        parsed = indian_to_number(val)

        if isinstance(parsed, tuple):
            df.at[i, f"{col}_min"] = parsed[0]
            df.at[i, f"{col}_max"] = parsed[1]
        else:
            df.at[i, f"{col}_min"] = parsed
            df.at[i, f"{col}_max"] = parsed


df.drop(price_cols, axis=1, inplace=True)



# -------------------------
# AREA NORMALIZATION
# -------------------------

def parse_area(col_name, value):
    if pd.isna(value):
        return np.nan

    # extract numeric
    try:
        area = float(re.sub("[^0-9.]", "", value))
    except:
        return np.nan
    
    # detect unit by column name
    name = col_name.lower()

    if "yd" in name or "yard" in name:
        return area * 0.836127
    elif "ft" in name or "sq.ft" in name:
        return area * 0.092903
    elif "m" in name and "sq" in name:
        return area
    else:
        return np.nan


area_cols = [c for c in df.columns if "builtup_area" in c.lower()]

for col in area_cols:
    df[f"{col}_m2"] = df[col].apply(lambda x: parse_area(col, x))


# ------------------------------------
# OPTIONAL: MELT THE AREA INTO LONG FORM
# ------------------------------------

area_long = df.melt(
    id_vars=['project'],
    value_vars=[c for c in df.columns if c.endswith("_m2")],
    var_name="area_type",
    value_name="area_m2"
)

# Similarly for prices (if needed)

In [27]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
df.head()

,property_title,avg_price,possession,seller_label,seller_subtitle,project,single_price,builtup_area,1 BHK Flat_min,1 BHK Flat_max,2 BHK Flat_min,2 BHK Flat_max,3 BHK Flat_min,3 BHK Flat_max,50 sq.yd Plot_min,50 sq.yd Plot_max,55 sq.yd Plot_min,55 sq.yd Plot_max,58 sq.yd Plot_min,58 sq.yd Plot_max,60 sq.yd Plot_min,60 sq.yd Plot_max,70 sq.yd Plot_min,70 sq.yd Plot_max,83 sq.yd Plot_min,83 sq.yd Plot_max,90 sq.yd Plot_min,90 sq.yd Plot_max,92 sq.yd Plot_min,92 sq.yd Plot_max,100 sq.yd Plot_min,100 sq.yd Plot_max,105 sq.yd Plot_min,105 sq.yd Plot_max,128 sq.yd Plot_min,128 sq.yd Plot_max,133 sq.yd Plot_min,133 sq.yd Plot_max,135 sq.yd Plot_min,135 sq.yd Plot_max,143 sq.yd Plot_min,143 sq.yd Plot_max,145 sq.yd Plot_min,145 sq.yd Plot_max,150 sq.yd Plot_min,150 sq.yd Plot_max,200 sq.yd Plot_min,200 sq.yd Plot_max,450 sq.ft Plot_min,450 sq.ft Plot_max,477 sq.ft Plot_min,477 sq.ft Plot_max,630 sq.ft Plot_min,630 sq.ft Plot_max,675 sq.ft Plot_min,675 sq.ft Plot_max,693 sq.ft Plot_min,693 sq.ft Plot_max,900 sq.ft Plot_min,900 sq.ft Plot_max,1188 sq.ft Plot_min,1188 sq.ft Plot_max,1215 sq.ft Plot_min,1215 sq.ft Plot_max,1251 sq.ft Plot_min,1251 sq.ft Plot_max,1269 sq.ft Plot_min,1269 sq.ft Plot_max,1323 sq.ft Plot_min,1323 sq.ft Plot_max,1332 sq.ft Plot_min,1332 sq.ft Plot_max,1350 sq.ft Plot_min,1350 sq.ft Plot_max,1395 sq.ft Plot_min,1395 sq.ft Plot_max,1449 sq.ft Plot_min,1449 sq.ft Plot_max,1485 sq.ft Plot_min,1485 sq.ft Plot_max,1611 sq.ft Plot_min,1611 sq.ft Plot_max,1800 sq.ft Plot_min,1800 sq.ft Plot_max,2205 sq.ft Plot_min,2205 sq.ft Plot_max,4680 sq.ft Plot_min,4680 sq.ft Plot_max,Studio Apartment_min,Studio Apartment_max,builtup_area_m2
0,"Residential Plots in New Palam Vihar Phase 1, Sector 110",₹2.89k/sq.yd,NaN,NaN,NaN,RBSM Colony Part 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"1, 2 BHK Flats in Sector 25, DLF Phase 2",₹4.5 K/sq.ft,NaN,NaN,NaN,DLF Chisholm Apartments,NaN,NaN,1125000.0,2025000.0,2475000.0,4275000.0,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Residential Plots in Rajoria Nagar,₹777.0/sq.ft,NaN,NaN,NaN,SDH Rose City,NaN,NaN,1125000.0,2025000.0,2475000.0,4275000.0,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN
3,"1, 2, 3 BHK Flats in Sector 35, Sohna",₹3.02 K - ₹4.5 K/sq.ft,NaN,NaN,NaN,Adore Prosperity Homes,NaN,NaN,1466000.0,1470000.0,2124000.0,2126000.0,2748000.0,2754000.0,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN
4,"1, 3 BHK Flats in Tech Chand Nagar, Sector 104","Dec, 2025",NaN,NaN,NaN,Mahira Homes 104,NaN,NaN,1384000.0,2640000.0,2124000.0,2126000.0,2629000.0,2640000.0,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN

In [29]:
# import pandas as pd
# import numpy as np
# import re

# # load your df
# df = pd.read_csv('/mnt/data/2_df.csv')

def _parse_single_value_in_inr(text: str):
    """Parse a single piece like '2.89k', '4.5 k', '777.0' to INR (float)."""
    t = text.strip().lower()
    # detect 'k' (thousands)
    if 'k' in t:
        num = re.sub(r'[^0-9.]', '', t)
        try:
            return float(num) * 1_000
        except ValueError:
            return np.nan
    else:
        num = re.sub(r'[^0-9.]', '', t)
        try:
            return float(num)
        except ValueError:
            return np.nan

def parse_avg_price_to_inr_per_sqm(x):
    """Convert strings like '₹4.5 K/sq.ft' or '₹3.02 K - ₹4.5 K/sq.ft'
       into integer INR per sq.meter."""
    if pd.isna(x):
        return np.nan
    
    s = str(x).strip().lower()

    # Filter out non-price strings like 'dec, 2025'
    if not any(ch.isdigit() for ch in s):
        return np.nan

    # Extract area unit: ft / yd / m / meter / mtr / mt
    unit_match = re.search(r'/\s*sq\.?\s*(ft|yd|m|meter|mtr|mt)', s)
    if unit_match:
        unit = unit_match.group(1)
    else:
        # no recognizable unit => skip
        return np.nan

    # Clean currency symbol & commas, remove the "/sq.xxx" part
    s_clean = s.replace('₹', '').replace(',', '')
    s_clean = re.sub(r'/\s*sq\.?\s*(ft|yd|m|meter|mtr|mt)', '', s_clean).strip()

    # Handle ranges: "a - b"
    if '-' in s_clean:
        parts = [p.strip() for p in s_clean.split('-') if p.strip()]
        nums = []
        for p in parts:
            nums.append(_parse_single_value_in_inr(p))
        nums = [n for n in nums if n is not None and not np.isnan(n)]
        if not nums:
            return np.nan
        value_per_unit = sum(nums) / len(nums)  # average of range
    else:
        value_per_unit = _parse_single_value_in_inr(s_clean)

    if value_per_unit is None or np.isnan(value_per_unit):
        return np.nan

    # Convert per-unit → per-square-meter
    if unit == 'ft':
        value_per_sqm = value_per_unit / 0.092903
    elif unit == 'yd':
        value_per_sqm = value_per_unit / 0.836127
    else:  # m / meter / mtr / mt -> already per m²
        value_per_sqm = value_per_unit

    # Return rounded integer INR / sq.m
    return int(round(value_per_sqm))


# Apply to your dataframe
df['avg_price_inr_per_sqm'] = df['avg_price'].apply(parse_avg_price_to_inr_per_sqm)

# Quick check
print(df[['avg_price', 'avg_price_inr_per_sqm']].head(10))

                avg_price  avg_price_inr_per_sqm
0            ₹2.89k/sq.yd                 3456.0
1            ₹4.5 K/sq.ft                48438.0
2            ₹777.0/sq.ft                 8364.0
3  ₹3.02 K - ₹4.5 K/sq.ft                40472.0
4               Dec, 2025                    NaN
5              ₹4 K/sq.ft                43056.0
6           ₹4.09 K/sq.ft                44024.0
7           ₹2.75 K/sq.ft                29601.0
8           ₹3.84 K/sq.ft                41333.0
9            ₹3.8 K/sq.ft                40903.0

In [30]:
df

,property_title,avg_price,possession,seller_label,seller_subtitle,project,single_price,builtup_area,1 BHK Flat_min,1 BHK Flat_max,2 BHK Flat_min,2 BHK Flat_max,3 BHK Flat_min,3 BHK Flat_max,50 sq.yd Plot_min,50 sq.yd Plot_max,55 sq.yd Plot_min,55 sq.yd Plot_max,58 sq.yd Plot_min,58 sq.yd Plot_max,60 sq.yd Plot_min,60 sq.yd Plot_max,70 sq.yd Plot_min,70 sq.yd Plot_max,83 sq.yd Plot_min,83 sq.yd Plot_max,90 sq.yd Plot_min,90 sq.yd Plot_max,92 sq.yd Plot_min,92 sq.yd Plot_max,100 sq.yd Plot_min,100 sq.yd Plot_max,105 sq.yd Plot_min,105 sq.yd Plot_max,128 sq.yd Plot_min,128 sq.yd Plot_max,133 sq.yd Plot_min,133 sq.yd Plot_max,135 sq.yd Plot_min,135 sq.yd Plot_max,143 sq.yd Plot_min,143 sq.yd Plot_max,145 sq.yd Plot_min,145 sq.yd Plot_max,150 sq.yd Plot_min,150 sq.yd Plot_max,200 sq.yd Plot_min,200 sq.yd Plot_max,450 sq.ft Plot_min,450 sq.ft Plot_max,477 sq.ft Plot_min,477 sq.ft Plot_max,630 sq.ft Plot_min,630 sq.ft Plot_max,675 sq.ft Plot_min,675 sq.ft Plot_max,693 sq.ft Plot_min,693 sq.ft Plot_max,900 sq.ft Plot_min,900 sq.ft Plot_max,1188 sq.ft Plot_min,1188 sq.ft Plot_max,1215 sq.ft Plot_min,1215 sq.ft Plot_max,1251 sq.ft Plot_min,1251 sq.ft Plot_max,1269 sq.ft Plot_min,1269 sq.ft Plot_max,1323 sq.ft Plot_min,1323 sq.ft Plot_max,1332 sq.ft Plot_min,1332 sq.ft Plot_max,1350 sq.ft Plot_min,1350 sq.ft Plot_max,1395 sq.ft Plot_min,1395 sq.ft Plot_max,1449 sq.ft Plot_min,1449 sq.ft Plot_max,1485 sq.ft Plot_min,1485 sq.ft Plot_max,1611 sq.ft Plot_min,1611 sq.ft Plot_max,1800 sq.ft Plot_min,1800 sq.ft Plot_max,2205 sq.ft Plot_min,2205 sq.ft Plot_max,4680 sq.ft Plot_min,4680 sq.ft Plot_max,Studio Apartment_min,Studio Apartment_max,builtup_area_m2,avg_price_inr_per_sqm
0,"Residential Plots in New Palam Vihar Phase 1, Sector 110",₹2.89k/sq.yd,NaN,NaN,NaN,RBSM Colony Part 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3456.0
1,"1, 2 BHK Flats in Sector 25, DLF Phase 2",₹4.5 K/sq.ft,NaN,NaN,NaN,DLF Chisholm Apartments,NaN,NaN,1125000.0,2025000.0,2475000.0,4275000.0,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48438.0
2,Residential Plots in Rajoria Nagar,₹777.0/sq.ft,NaN,NaN,NaN,SDH Rose City,NaN,NaN,1125000.0,2025000.0,2475000.0,4275000.0,NaN,NaN,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN,8364.0
3,"1, 2, 3 BHK Flats in Sector 35, Sohna",₹3.02 K - ₹4.5 K/sq.ft,NaN,NaN,NaN,Adore Prosperity Homes,NaN,NaN,1466000.0,1470000.0,2124000.0,2126000.0,2748000.0,2754000.0,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN,40472.0
4,"1, 3 BHK Flats in Tech Chand Nagar, Sector 104","Dec, 2025",NaN,NaN,NaN,Mahira Homes 104,NaN,NaN,1384000.0,2640000.0,2124000.0,2126000.0,2629000.0,2640000.0,1300000.0,1300000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600000.0,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3900000.0,3900000.0,5200000.0,5200000.0,350000.0,350000.0,NaN,NaN,NaN,NaN,524000.0,524000.0,NaN,NaN,699000.0,699000.0,NaN,NaN,NaN,NaN,972000.0,972000.0,NaN,NaN,1028000.0,1028000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Residential Plot in Dhankot,₹1.0k/sq.ft,NaN,NaN,NaN,NaN,₹4.5L,450 sq.ft,697000.0,1309000.0,2000000.0,2000000.0,2156000.0,2156000.0,750000.0,750000.0,660000.0,660000.0,700000.0,700000.0,720000.0,720000.0,840000.0,840000.0,1000000.0,1000000.0,1080000.0,1080000.0,1110000.0,1110000.0,1500000.0,1500000.0,1266000.0,1266000.0,1540000.0,1540000.0,1596000.0,1596000.0,1620000.0,1620000.0,1720000.0,1720000.0,1748000.0,1748000.0,1800000.0,1800000.0,2399000.0,2399000.0,325000.0,325000.0,276000.0,276000.0,364000.0,364000.0,524000.0,524000.0,401000.0,401000.0,650000.0,650000.0,687000.0,687000.0,702000.0,702000.0,972000.0,972000.0,733000.0,733000.0,765000.0,765000.0,770000.0,770000.0,780000.0,780000.0,806000.0,806000.0,838000.0,838000.0,858000.0,858000.0,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,1000000.0,1000000.0,NaN,10764.0
68,Residential Plot in Sultanpur,₹8.5k/sq.yd,NaN,NaN,NaN,NaN,₹4.25L,50 sq.yd,697000.0,1309000.0,2000000.0,2000000.0,2156000.0,2156000.0,750000.0,750000.0,660000.0,660000.0,700000.0,700000.0,720000.0,720000.0,840000.0,840000.0,1000000.0,1000000.0,1080000.0,1080000.0,1110000.0,1110000.0,1500000.0,1500000.0,1266000.0,1266000.0,1540000.0,1540000.0,1596000.0,1596000.0,1620000.0,1620000.0,1720000.0,1720000.0,1748000.0,1748000.0,1800000.0,1800000.0,2399000.0,2399000.0,325000.0,325000.0,276000.0,276000.0,364000.0,364000.0,524000.0,524000.0,401000.0,401000.0,650000.0,650000.0,687000.0,687000.0,702000.0,702000.0,972000.0,972000.0,733000.0,733000.0,765000.0,765000.0,770000.0,770000.0,780000.0,780000.0,806000.0,806000.0,838000.0,838000.0,858000.0,858000.0,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,1000000.0,1000000.0,NaN,10166.0
69,Residential Plot in Shahid Smarak,₹648.00/sq.ft,NaN,NaN,NaN,NaN,₹3.5L,540 sq.ft,697000.0,1309000.0,2000000.0,2000000.0,2156000.0,2156000.0,750000.0,750000.0,660000.0,660000.0,700000.0,700000.0,720000.0,720000.0,840000.0,840000.0,1000000.0,1000000.0,1080000.0,1080000.0,1110000.0,1110000.0,1500000.0,1500000.0,1266000.0,1266000.0,1540000.0,1540000.0,1596000.0,1596000.0,1620000.0,1620000.0,1720000.0,1720000.0,1748000.0,1748000.0,1800000.0,1800000.0,2399000.0,2399000.0,325000.0,325000.0,276000.0,276000.0,364000.0,364000.0,524000.0,524000.0,401000.0,401000.0,650000.0,650000.0,687000.0,687000.0,702000.0,702000.0,972000.0,972000.0,733000.0,733000.0,765000.0,765000.0,770000.0,770000.0,780000.0,780000.0,806000.0,806000.0,838000.0,838000.0,858000.0,858000.0,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,1000000.0,1000000.0,NaN,6975.0
70,"2 BHK Flat in Laxman Vihar, Sector 3A",₹471.00/sq.ft,NaN,NaN,NaN,NaN,₹3.3L,700 sq.ft,697000.0,1309000.0,2000000.0,2000000.0,2156000.0,2156000.0,750000.0,750000.0,660000.0,660000.0,700000.0,700000.0,720000.0,720000.0,840000.0,840000.0,1000000.0,1000000.0,1080000.0,1080000.0,1110000.0,1110000.0,1500000.0,1500000.0,1266000.0,1266000.0,1540000.0,1540000.0,1596000.0,1596000.0,1620000.0,1620000.0,1720000.0,1720000.0,1748000.0,1748000.0,1800000.0,1800000.0,2399000.0,2399000.0,325000.0,325000.0,276000.0,276000.0,364000.0,364000.0,524000.0,524000.0,401000.0,401000.0,650000.0,650000.0,687000.0,687000.0,702000.0,702000.0,972000.0,972000.0,733000.0,733000.0,765000.0,765000.0,770000.0,770000.0,780000.0,780000.0,806000.0,806000.0,838000.0,838000.0,858000.0,858000.0,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,1000000.0,1000000.0,NaN,5070.0
71,Residential Plot in Patel Nagar,₹944.00/sq.ft,NaN,NaN,NaN,NaN,₹1.7L,180 sq.ft,697000.0,1309000.0,2000000.0,2000000.0,2156000.0,2156000.0,750000.0,750000.0,660000.0,660000.0,700000.0,700000.0,720000.0,720000.0,840000.0,840000.0,1000000.0,1000000.0,1080000.0,1080000.0,1110000.0,1110000.0,1500000.0,1500000.0,1266000.0,1266000.0,1540000.0,1540000.0,1596000.0,1596000.0,1620000.0,1620000.0,1720000.0,1720000.0,1748000.0,1748000.0,1800000.0,1800000.0,2399000.0,2399000.0,325000.0,325000.0,276000.0,276000.0,364000.0,364000.0,524000.0,524000.0,401000.0,401000.0,650000.0,650000.0,687000.0,687000.0,702000.0,702000.0,972000.0,972000.0,733000.0,733000.0,765000.0,765000.0,770000.0,770000.0,780000.0,780000.0,806000.0,806000.0,838000.0,838000.0,858000.0,858000.0,1252000.0,1252000.0,1399000.0,1399000.0,1713000.0,1713000.0,3636000.0,3636000.0,1000000.0,1000000.0,NaN,10161.0

In [31]:
df.to_csv("2_df.csv", index = False)